### ISSUE TITLE
Possible to get this working inside an iframe?

### ISSUE THREAD

**Issue by volkandkaya** [alexkatz/react-tiny-popover#30]
Trying to get it working inside an iframe but it doesn't align to the HTML element.

I'm trying to use 
`contentLocation={{
   left:left + rect.left,
   top: top + rect.top - 6 + plus + (rect.onClickTop || 0) - (rect.offsetTop || 0)
}}`

**Comment by alexkatz** [comment]
The problem here is unclear to me, as all [code sandboxes](https://codesandbox.io/s/unruffled-ellis-8mggbd?file=/src/App.js) demonstrate popovers working within iframes.

Going to close this, but please open an issue describing a specific issue in more detail if you're still running into this problem.
