### ISSUE TITLE
Popover renders in the wrong position when the target is offscreen.

### ISSUE THREAD

**Issue by dmitrif** [alexkatz/react-tiny-popover#41]
**Issue**
When repositioning is `true`, the nudged position is calculated incorrectly for when the target is scrolled off screen.

**Current**
![wrong](https://user-images.githubusercontent.com/655800/64969514-0ef02000-d872-11e9-8e52-e927a16ca810.gif)

**Desired**
![right](https://user-images.githubusercontent.com/655800/64969594-35ae5680-d872-11e9-9221-b43b2315fbb2.gif)

This is happening due to the nudgePosition function discarding the calculated top position, when it is less than the `windowPadding` value.

PR incoming.

**Comment by dmitrif** [comment]
@bengry No, ended up switching to `react-popover` as the investment to rewrite the positioning logic here was a bit too high to fit into my timebox.

**Comment by alexkatz** [comment]
Hi all, I've recently released version 6 of `react-tiny-popover`, which is a completely functional and hooks-based overhaul. The above issue is no longer present, as the API of `react-tiny-popover` now allows users to specify a `containerParent` whose boundaries are to be adhered to, rather than always defaulting to `window`. 

This makes the following behavior possible:

![popover-demo](https://user-images.githubusercontent.com/4224538/101695282-539d4380-3a42-11eb-98c0-8d54b587be64.gif)

I'll close this for now, and apologies for not replying sooner!
